appacademy/cohort-resources

- README.md
> add holidays

- README.md
> remove individual instructors from main readme

- study_guides/canvas/canvas.md
Added some additional canvas methods and comments to instructions on drawing a circle.
> Add additional instructions to canvas

- README.md
I've added subsection hyperlinks to the student and instructor sections. In addition, I snake_cased all the Folder Breakdown folder names and capitalized some other header names for a more uniform styling.
> Add subsection hyperlinks and make header naming styles uniform

- assessment_tips/foundations_2/dog.rb
- assessment_tips/foundations_2/map.rb
- assessment_tips/react_1/react_1_notes.md
- assessment_tips/ruby_1/assessment_tips.md
I fixed some smaller typos in a couple files, but mainly I added an entire react 1 assessment notes file. The previous file was just blank, so I added some bullets and links. If you can think of any additional bullets to add just let me know!
> Fix typos and add react 1 assessment notes

- study_guides/javascript/currying_myBind_debugger/currying_myBind_debugger.js
- study_guides/javascript/javascript_fundamentals.md
- study_guides/javascript/vanilla_javascript_cheatsheet.md
- study_guides/javascript_project/README.md
I added an example to currying which uses a new object, added styling and more selectors to the Vanilla DOM worksheet, and added a link to the github pages docs
> Add example to curry and add to Vanilla DOM cheatsheet

- lectures/w8d5-moreJavaScript/slides.md
> Add More JavaScript Slides

- lectures/README.md
adding bluebird link to cohort resources
> Add bluebird link

- study_guides/rails/edit_and_update.md
Josh and Carlos please add any additional reviewers from assessments and cohort resources as you see fit. Thanks!
> IN-118 edit/update study guide

- common_bugs/setup_bugs/README.md
added a noko giri bug that a student came across when they tried to bundle install in a rails project.
> add nokogiri bug

- README.md
this should update the branch to have new yorks email
> add ny instructors emails to master branch

- lectures/w11d1-fsp-schema-sample-state/lecture-2-mvp-schema-stateShape.md
> add schema lecture

- lectures/W3D2-references-scope/slides.md
- lectures/W3D2-references-scope/test.rb
Add References slides and demo
> Add references slides / demo

- lectures/W4D2-OOP/farm.rb
- lectures/W4D2-OOP/slides.md
> Add OOP demo and slides

- study_guides/full_stack_project/things_to_consider.md
Let me know if you want it in another file or want to change the wording
> Add fsp advice list

- lectures/W4D5-big-o/slides.md
- lectures/W4D5-big-o/time_complexity_demo.rb
> Add w4d5 big o lecture slides and demo

- lectures/README.md
> Add new Bluebird demo link to readme

- lectures/W6D2-metaprogramming/demos/meta.rb
- lectures/W6D2-metaprogramming/slides.md
slides and demo for W6D2 metaprogramming
> Add W6D2 metaprogramming slides and demo

- lectures/W6D5-rails-views/slides.md
> Add W6D5 rails views lecture slides

- lectures/w1d4/css_intro/.vscode/settings.json
- lectures/w1d4/css_intro/demos/README.md
- lectures/w1d4/css_intro/demos/box-model.css
- lectures/w1d4/css_intro/demos/box-model.html
- lectures/w1d4/css_intro/demos/reset.css
- lectures/w1d4/css_intro/demos/reset.html
- lectures/w1d4/css_intro/demos/selectors.css
- lectures/w1d4/css_intro/demos/selectors.html
- lectures/w1d4/css_intro/demos/selectors_solution.css
- lectures/w1d4/css_intro/slides.md
- lectures/w1d4/html/demo/README.md
- lectures/w1d4/html/demo/assets/main.css
- lectures/w1d4/html/demo/assets/printName.js
- lectures/w1d4/html/demo/index.html
- lectures/w1d4/html/slides.md
> add w1d4 lecture

- lectures/W10D1-react/jobListings/.gitignore
- lectures/W10D1-react/jobListings/frontend/entry.jsx
- lectures/W10D1-react/jobListings/frontend/jobIndex.jsx
- lectures/W10D1-react/jobListings/frontend/jobIndexItem.jsx
- lectures/W10D1-react/jobListings/frontend/widget.jsx
- lectures/W10D1-react/jobListings/index.html
- lectures/W10D1-react/jobListings/package-lock.json
- lectures/W10D1-react/jobListings/package.json
- lectures/W10D1-react/jobListings/webpack.config.js
- lectures/W10D1-react/slides.md
Add slides and demo for React day!
> Add demo and slides for React

- lectures/w2d2/lecture/attr-methods/dog.rb
- lectures/w2d2/lecture/requiring-files/clean-code/college.rb
- lectures/w2d2/lecture/requiring-files/clean-code/student.rb
- lectures/w2d2/lecture/requiring-files/messy-code/messy-code.rb
- lectures/w2d2/lecture/syntactic-sugar/board.rb
- lectures/w2d2/lecture/syntactic-sugar/number.rb
- lectures/w2d2/lecture/user-input/gets.rb
- lectures/w2d2/videos/attr-methods.rb
- lectures/w2d2/videos/requiring_files/cat.rb
- lectures/w2d2/videos/requiring_files/other_animals/dog.rb
- lectures/w2d2/videos/requiring_files/pet_hotel.rb
- lectures/w2d2/videos/syntactic-sugar/person.rb
- lectures/w2d2/videos/syntactic-sugar/queue.rb
- lectures/w2d2/videos/user_input/user_input_demo.rb
> Add W2D2 lecture

- common_bugs/setup_bugs/README.md
I moved this bulletpoint to correct these instructions
> Move bulletpoint on rails 6 instructions

- lectures/w4d2-oop/demo/enumerable.rb
- lectures/w4d2-oop/demo/farm.rb
- lectures/w4d2-oop/slides.md
> Add slides and demo for OOP

- lectures/W6D2/meta.rb
- lectures/W6D2/slides.md
Add W6D2 meta programing demo and slides
> W6D2 meta programing

- full_stack_projects/aa_approved_full_stack_projects.md
- full_stack_projects/mvp_guidelines.md
Please read through the list and double check the Features/Bonuses. We didn't have listed features/bonuses for some of apps on our approved list so I selected ones that focused on the core of the apps.
> FSP approved list of app to clone

- full_stack_projects/full_stack_auth_cheatsheet.md
Please review and let me know if you find anything amiss
sheet steps through user auth from back to front including backend configuration setup.
> Add full stack auth cheat sheet
